[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    # "unsafe-none" est la valeur par défaut la plus permissive.
    # Cela permet à la popup Google d'accéder à votre fenêtre principale sans blocage.
    Cross-Origin-Opener-Policy = "unsafe-none"
    Cross-Origin-Embedder-Policy = "unsafe-none"
    
    # Sécurité standard pour les autres aspects
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"